@startuml
hide empty members

enum CartaAccionTipo {
  PICO
  ANTORCHA
  MINECART
  VACIO
}

enum Rol {
  IMPOSTOR
  ENANO
}

class Cliente{
  .. Constructor ..
  + Cliente(String : ip, int : puerto)
  .. Metodos ..
  + void : iniciar(Object : objeto)
}

class AppCliente{
  Atributos
  --
  - {static} VistaGUI : vista
  - {static} ControladorGUI : controlador
  .. Main ..
  + {static} void : main(String[] : args)
  .. Metodos ..
  + void : start(Stage : stage)
}

class ControladorGUI{
  Atributos
  --
  - ITablero : modelo
  - VistaGUI : vista
  - String : nombreJugadorDeEsteControlador
  - boolean : juegoEnMarcha
  .. Constructor ..
  + ControladorGUI(VistaGUI : vista)
  .. Metodos ..
  + void : iniciar
  + void : jugadorListo
  + void : ponerCartaSobreTablero(int : posCarta, int : pos)
  + void : ponerCartaSobreJugador(int : posCarta, String : nombre)
  + void : actualizarDatosVista()
  + void : actualizar(IObservableRemoto : instanciaDeModelo, Object : cambio)
  + <T extends IObservableRemoto>void : setModeloRemoto(T : modeloRemoto)

}

class VistaGUI{
  Atributos
  --
  - ArrayList<String> : nombres
  - final int : MAX
  - int : cartasRestantesMazo
  - Jugador : jugador
  - String : jugadorActual
  - ArrayList<Jugador> : adversarios
  - Slots_tablero : tableroJuego
  - int : largoTablero
  - ControladorGUI : controlador
  - String : nombreJugador
  - Top : top
  - int : slotSeleccionado
  Atributos FXML
  --
  - Label : labelEstado
  - Label : labelNombreJugador
  - Label : labelRolJugador
  - Label : turnoActual
  - Label : labelCartasRestantes
  - Label : labelOrosVistos
  - ListView<String> : listaFaltan
  - Button : botonListo
  - GridPane : botonesTablero
  - ScrollPane : scrollTablero
  - Label : labelManoTitulo
  - VBox : contenedorRestricciones
  - VBox : contenedorMano
  - ToggleGroup : tgMano
  - VBox : contenedorJugadores
  - ToggleGroup : tgAdversarios
  - VBox : contenedorOrosVistos
  - VBox : opciones
  - Button : jugarEnUnJugador
  - Button : jugarEnElTablero
  - Button : descartarLaCarta
  .. Constructor ..
  + VistaGUI()
  .. Setters ..
  + void : setControlador(ControladorGUI : controlador)
  + void : setLargo(int : largo)
  + void : setNombreJugador(String nombre)
  + void : setTop(Top : top)
  + void : setJugador(Jugador : j)
  + void : setAdversarios(ArrayList<Jugador> : adversarios)
  + void : actualizarSala(int : listos, int : totalJugadores, List<String> : faltan)
  + void : actualizarTablero(Slots_tablero : tablero)
  + void : actualizarCartasRestantes(int : cantidad)
  + void : jugadorSiguiente(String : j)
  .. Getters ..
  + String : getNombre()
  .. Metodos FXML..
  + void : initialize()
  + void : clickListo()
  + void : mostrarError(String : mensaje)
  + void : mostrarTop()
  .. Otros ..
  + boolean : confirmarListo()
  + void : mostrarEstadoSala(EstadoSala : estado)
  + void : mostrarTodosListos()
  + void : cambiarAEscenarioJuego()
  + void : iniciarJuego(int : largo)
  + void : vistaPorDefecto()
  + void : verTablero()
  + void : opcionesBotones()
  + void : mostrarFinDeJuego()
  .. Metodos Privados ..
  - void : deshabilitarTodos()
  - void : verJugadorActual()
  - void : verCartasJugador()
  - void : verOtrosJugadores()
  - void : verOrosJugador()
  - void : verRestriccionesJugador()
  - void : verCantidadDeCartasRestantes()
  - String : cartaAString(Carta : c)
 
}


interface ITablero{
  + int : getLargo()
  + boolean : esJugable()
  + void : agregarJugador(String : nombre)
  + void : agregarJugadores(Arraylist<String> : jugadoresNuevos)
  + void : iniciarJuego()
  + Slots_tablero : getTableroConSlots()
  + int : getCantidadRestanteMazo()
  + void ponerCartaSobreJugador(int : posCarta, String : jugadorObjetivo, String quien)
  + void : ponerCartaSobreTablero(int : posCarta, String : quien)
  + void : descartarCarta(int : posCarta, String : quien)
  + EstadoSala marcarListo(String : nombre)
  + void : intentarArrancarElJuego()
  + boolean : estoyLogueado(String nombre)
  + Jugador : devolverJugador(String nombre)
  + String : getJugadorSiguiente()
  + Arraylist<Jugador> : getListaAdversarios(String quien)
  + String : getPartidaGanada()
  + Top : getTop()
}


class Jugador {
  Atributos
  --
  - {static} long : serialVersionUID
  - String : nombre
  - ArrayList<Carta> : mano
  - ArrayList<CartaSabotaje> : restricciones
  - ArrayList<Carta_Camino> : orosVistos
  - Rol : rol
  .. Constructor ..
  + Jugador(String : n, ArrayList<Carta> : m, Rol : r) 
  .. Getters ..
  + ArrayList<Carta> : getManoJugador() 
  + ArrayList<Carta_Oro> : getOrosJugador() 
  + ArrayList<CartaSabotaje> : getRestriccionesJugador()
  + String : getNombre()
  + Rol : getRol()
  + int : getPuntos()
  + boolean : tieneRestricciones()
  .. Setters ..
  + boolean : agregarRestriccion(Carta) 
  + boolean : quitarRestriccion(Carta)
  + boolean : tieneRestricciones()
  + void : agregarOrosVistos(Carta)
  + void : sumarPuntosJugador(int : puntos)
}


class Carta {
  Atributos
  --
  - {static} long : serialVersionUID  
}

class CartaReparacion {
  Atributos
  --
  - {static} long : serialVersionUID
  - CartaAccionTipo : reparacion1 
  - CartaAccionTipo : reparacion2 
  .. Constructor .. 
  + CartaReparacion(CartaAccionTipo : re1, CartaAccionTipo : re2)
  .. Getters ..
  + CartaAccionTipo : getReparacion1() 
  + CartaAccionTipo : getReparacion2()  
}

class CartaSabotaje {
  Atributos
  --
  - {static} long : serialVersionUID
  - CartaAccionTipo : sabotaje
  .. Constructor ..
  + CartaSabotaje(CartaAccionTipo : sabotaje)
  .. Getters ..
  + CartaAccionTipo : getAccion() 
}
class CartaSimple {
  Atributos
  --
  - {static} long : serialVersionUID
  - boolean : derrumbe
  - boolean : vista
  .. Constructor ..
  + CartaSimple(boolean : vista)
  .. Getters ..
  + boolean : esVista()
  + boolean : esDerrumbe() 
}

class Carta_Camino {
  Atributos
  --
  - {static} long : serialVersionUID
  - boolean : callejon
  - Strig : forma
  - boolean : arriba
  - boolean : abajo
  - boolean : izquierda
  - boolean : derecha 
  - boolean : meta
  - boolean : oro
  .. Constructor ..
  + Carta_Camino(boolean : meta, boolean : oro)
  + Carta_Camino(boolean : callejon,boolean : ar,boolean : ab,boolean : iz,boolean : de,String : f)
  .. Getters ..
  + boolean : getArriba()
  + boolean : getAbajo()
  + boolean : getIzquierda()
  + boolean : getDerecha()
  + boolean : getForma()
  + boolean : esUnCallejon()
  + boolean : esMeta()
  + boolean : getOro()
}


class Slot {
  Atributos
  --
  - {static} long : serialVersionUID
  - Carta_Camino : carta_alojada
  - Slot : arriba
  - Slot : abajo
  - Slot : izquierda
  - Slot : derecha
  - String : forma
  .. Constructor ..
  + Slot()
  + Slot(Slot : ar, Slot : ab, Slot : iz, Slot : de)
  + Slot(Carta_Camino : carta)
  + Slot(Carta_Camino : carta, Slot : ar, Slot : ab, Slot : iz, Slot : de)
  .. Setters ..
  + void : Slot_Set_Arriba(Slot : slot)
  + void : Slot_Set_Abajo(Slot : slot)
  + void : Slot_Set_Izquierda(Slot : slot)
  + void : Slot_Set_Derecha(Slot : slot)
  + void : SlotSetForma(String formaNueva)
  
  .. Getters ..
  + boolean : taOcupao() 
  + Carta_Camino : getCartaAlojadaEnSlot(): 
  + boolean : slotConectadoALaMeta()
  + boolean : alojarCarta(Carta cartaRecibida)
  + eliminarCarta(): void
  
  .. Metodos Privados ..
  - void : checkConexionMeta(Slot : slot)
}

class Slots_tablero {
  Atributos
  --
  - {static} long : serialVersionUID
  - ArrayList<Slot> : slots
  - ArrayList<Carta_Camino> mazo_oro
  - int largoTablero
  .. Constructor ..
  + Slots_tablero(int : largo)
  .. Metodos Privados ..
  - void : crear_slots()
  .. Getters ..
  + Slot : getSlot(int)
}

class JugadorHistorico{
  Atributos
  --
  - {static} long : serialVersionUID
  - String : nombre
  - int : puntos
  .. Constructor ..
  + JugadorHistorico()
  .. Setters ..
  + void : sumarPuntos(int : cantidad)
  + void : setNombre(String nombre)
  .. Getters ..
  + String : getNombre()
  + int : getPuntos()
}

class Top{
  Atributos
  --
  - {static} long : serialVersionUID
  - ArrayList<JugadorHistorico> top
  .. Constructor ..
  + Top()
  .. Setters ..
  + void : agregarPuntosHistorico(String : name, int : cantidad)
  .. Gettets ..
  + ArrayList<JugadorHistorico> : getHistorico()
}
class EstadoSala{
  Atributos
  --
  - {static} long : serialVersionUID
  - int totalJugadores
  - int listos
  - List<String> faltan
  .. Constructor ..
  + EstadoSala(int : total, int : listos, List<String> : faltan)

}

interface IControladorRemoto{
}

class Mazo_oros { 
  Atributos
  --
  - {static} long : serialVersionUID
  - ArrayList<Carta_Camino> : mazo_oro
  .. Constructor ..
  + Mazo_oros()
  .. Metodos Privados ..
  - void : oros()
  .. Getters ..
  + ArrayList<Carta_Camino> : get_mazo_oros() 
}

AppCliente --> VistaGUI : instancia
AppCliente --> ControladorGUI : instancia
AppCliente --> Cliente : instancia 

Cliente --> ControladorGUI : tiene

ControladorGUI ..|> IControladorRemoto : implementa
ControladorGUI --> IObservableRemoto: conoce
ControladorGUI --> VistaGUI : contiene
ControladorGUI --> ITablero : contiene

VistaGUI --> ControladorGUI : tiene
VistaGUI --> Jugador : contiene
VistaGUI --> Slots_tablero : tiene
VistaGUI --> Top : tiene
VistaGUI ..> CartaSabotaje : utiliza
VistaGUI ..> CartaReparacion : utiliza
VistaGUI ..> CartaSabotaje : utiliza
VistaGUI ..> Carta_Camino : utiliza
VistaGUI ..> Carta : utiliza
VistaGUI ..> EstadoSala : utiliza


Mazo_oros --> Carta_Camino : tiene

Carta <|-- CartaReparacion
Carta <|-- CartaSabotaje
Carta <|-- Carta_Camino
Carta <|-- CartaSimple 


Jugador ..> Rol : utiliza
Jugador "1"-->"0..*" CartaSabotaje : utiliza
Jugador "1"-->"0..*" CartaReparacion : utiliza
Jugador "1"-->"0..*" CartaSabotaje : utiliza
Jugador "1"-->"0..*" Carta_Camino : utiliza
Jugador "1"-->"0..*" Carta : utiliza

CartaReparacion ..> CartaAccionTipo : utiliza
CartaSabotaje ..> CartaAccionTipo : utiliza

Slots_tablero "1" --> "*" Slot : aloja
Slots_tablero --> Mazo_oros : utiliza

Slot "1" --> "1" Carta_Camino : aloja
Slot ..> CartaSimple : utiliza


Top "1"-->"*" JugadorHistorico : tiene

ITablero ..> Slots_tablero : dependencia
ITablero ..> EstadoSala
ITablero ..> Jugador
ITablero ..> Top



@enduml
